-- Add 5 new tours to the production database
-- Safe to run multiple times (slug is UNIQUE, ON DUPLICATE KEY UPDATE makes it idempotent)
-- Run in phpMyAdmin: select the aventra database -> SQL tab -> paste -> Go

INSERT INTO tours (title, slug, short_description, description, status, image_url, price, deposit_price, currency, duration_days, difficulty, location, country, region, max_capacity, available_spots, next_date) VALUES
('Bestig Kilimanjaro', 'bestig-kilimanjaro', '8 dagar på berget. Vandra genom fyra klimatzoner till toppen av Afrika.', 'Vandra genom fyra klimatzoner på vår unika rutt till toppen av Afrika, Uhuru Peak 5895 m höjd. En expedition utöver det vanliga med erfarna guider.', 'active', 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=800', 45900.00, 5000.00, 'SEK', 10, 'hard', 'Kilimanjaro', 'Tanzania', 'East Africa', 12, 4, '2027-01-24'),
('Vandra Inkaleden', 'vandra-inkaleden', '12 dagar. Vi vandrar på vår obefolkade rutt av Inkaleden.', 'Vi vandrar på vår obefolkade rutt av Inkaleden, utan trängsel, fram till slutmålet – Machu Picchu! En klassisk expedition.', 'active', 'https://images.unsplash.com/photo-1483389127117-b6a2102724ae?q=80&w=800', 45900.00, 4500.00, 'SEK', 12, 'hard', 'Machu Picchu', 'Peru', 'South America', 12, 6, '2027-04-30'),
('Jämtlandsfjällen', 'jamtlandsfjallen', '5 dagar. Fjällvandring bland kala toppar och glittrande fjällsjöar.', 'Upptäck Jämtlandsfjällen med oss – en fjällvandring genom ett av Sveriges vackraste fjällområden. Vi vandrar på leder mellan fjällstationer och njuter av stillheten och den storslagna naturen.', 'active', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800', 12900.00, 1500.00, 'SEK', 5, 'moderate', 'Jämtland', 'Sweden', 'Scandinavia', 12, 8, '2027-06-15'),
('Touch av Sarek', 'touch-av-sarek', '7 dagar. En smak av Sarek – vandring i Sveriges mest vilda nationalpark.', 'Upplev Sareks nationalpark, Europas sista vildmark. Vi vandrar genom sagolika dalar omgivna av höga toppar och glaciärer. En äkta vildmarksupplevelse med erfarna guider.', 'active', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800', 18900.00, 2000.00, 'SEK', 7, 'hard', 'Sarek National Park', 'Sweden', 'Lapland', 10, 6, '2027-07-10'),
('Everest Base Camp', 'everest-base-camp', '14 dagar. Vandra den unika Gokyo-rutten fram till Everest BC.', 'Vandra den unika Gokyo-rutten fram till Everest BC. Från Base Camp tar vi helikopter tillbaka ned. En expedition med svensk guide.', 'active', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=800', 45900.00, 4500.00, 'SEK', 14, 'hard', 'Everest Region', 'Nepal', 'Himalayas', 10, 3, '2027-03-23')
ON DUPLICATE KEY UPDATE slug=slug;
